// Generated by https://quicktype.io

export interface BasicResponse {
    lon:       number;
    fint:      string;
    prec:      number;
    alt:       number;
    vmax:      number;
    vv:        number;
    dv:        number;
    lat:       number;
    dmax:      number;
    pres:      number;
    hr:        number;
    pres_nmar: number;
    tamin:     number;
    ta:        number;
    tamax:     number;
    tpr:       number;
    rviento:   number;
}

