// Generated by https://quicktype.io

export interface AEMETBasicResponse {
    idema:     Idema;
    lon:       number;
    fint:      string;
    prec:      number;
    alt:       number;
    vmax:      number;
    vv:        number;
    dv:        number;
    lat:       number;
    dmax:      number;
    ubi:       Ubi;
    pres:      number;
    hr:        number;
    pres_nmar: number;
    tamin:     number;
    ta:        number;
    tamax:     number;
    tpr:       number;
    rviento:   number;
}

export enum Idema {
    C659M = "C659M",
}

export enum Ubi {
    LasPalmasDeGcPlazaDeLaFeria = "LAS PALMAS DE GC. PLAZA  DE LA FERIA",
}
